# Generated by Django 5.1.1 on 2024-09-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_converction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="converction",
            name="answer",
            field=models.TextField(default=False),
        ),
    ]
