# Generated by Django 5.1.1 on 2024-09-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_aiinformation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiinformation",
            name="company",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="aiinformation",
            name="hardwerrequired",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="aiinformation",
            name="limitations",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="aiinformation",
            name="securityfeatures",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="aiinformation",
            name="userfeedback",
            field=models.TextField(),
        ),
    ]
