# Generated by Django 5.1.1 on 2024-09-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_aiinformation_company_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiinformation",
            name="costofmonth",
            field=models.CharField(default="0", max_length=200),
        ),
        migrations.AlterField(
            model_name="aiinformation",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
